# Generated by Django 4.1.3 on 2023-04-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'NullMote'), (1, 'WMote'), (2, 'EMote')], default=0)),
                ('sector', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_collection', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('collect_date', models.DateTimeField()),
                ('mote', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.motes')),
            ],
        ),
    ]
