# Generated by Django 4.1.7 on 2023-04-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motes',
            old_name='sector',
            new_name='section',
        ),
    ]
