# Generated by Django 4.1.7 on 2023-05-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sector_motes_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='collect_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='StatsMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('std', models.FloatField()),
                ('cv', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('fq', models.FloatField()),
                ('tq', models.FloatField()),
                ('mote', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.motes')),
            ],
        ),
    ]
