# Generated by Django 4.1.7 on 2023-05-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_data_collect_date_statsmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatsMin',
            new_name='StatsHour',
        ),
    ]
