# Generated by Django 4.1.7 on 2023-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_statsmin_statshour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statshour',
            name='cv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statshour',
            name='fq',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statshour',
            name='max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statshour',
            name='mean',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statshour',
            name='median',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statshour',
            name='min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statshour',
            name='std',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statshour',
            name='tq',
            field=models.FloatField(default=0),
        ),
    ]
